#This code is perfectly fine. Should give no errors#

func int fact(int r)
{
	return r*fact(r-1);
}

func int fib(int n)#function#
{
	if (n==1)
		return 1;
	else if(n==2)
		return 1;
	else
		return fib(n-1) + fib(n-2);
}

print("12th fibonacci is" + fib(12));

while(1)
{
	print ("Infinite loop");
} #Note: print will come out as an identifier since it is a function name#
